import type { NextPage } from 'next'
import { Box, Button, Flex, Grid, Heading, IconButton, ListItem, Spacer, Text, useColorMode } from '@chakra-ui/react'
import { DownloadIcon } from '@heroicons/react/outline'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { decorateComponent } from '../utilities/decorateComponent'


const HomePage: NextPage = () => {
    return (
        <div className={styles.container}>

            <Head>
                <title>Daniel Hernández</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Box flexDirection="column" alignItems="flex-start" marginBottom="48">
                <Box
                    overflow="hidden"
                    marginY="6"
                    position="relative"
                    borderRadius="50%"
                    maxWidth="max-content">
                    <Image
                        width="156"
                        height="156"
                        src="/profile-light.png">
                    </Image>
                </Box>
                <Heading color="secondary.default" size="lg" marginBottom="6">
                    Hi, I'm Daniel Hernández
                </Heading>
                <Heading size="3xl">
                    I bring to life <Text fontWeight="700" color="primary.default" display="inline">stunning<br /> web applications.</Text>
                </Heading>

                <Text fontSize="xl" marginTop="6">
                    I’m a frontend developer based in Bogotá, CO with a strong design & backend<br /> experience. Currently working for ByPeople as Technical Lead Engineer.
                </Text>
            </Box>


            <Box flexDirection="column" alignItems="flex-start">
                <Heading size="2xl">
                    Latest blog posts
                </Heading>

                <Text fontSize="xl" marginTop="6" marginBottom="14">
                    I’m constantly writing about what I learn & sharing my experiences on the<br /> work. Hope you find useful content here or at least learn something new.
                </Text>


                <Grid width="100%" templateColumns='repeat(auto-fill, minmax(350px, 1fr))' gap={10}>
                    <Box border="1px" borderColor="whiteAlpha.100">
                        <Box height={300} background="whiteAlpha.100"></Box>
                        <Box paddingY="8" paddingX="6">
                            <Heading marginBottom="4" size="md">
                                Here goes a sample title for any random article post I will write
                            </Heading>
                            <Text fontSize="lg">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...
                            </Text>
                        </Box>
                    </Box>
                    <Box border="1px" borderColor="whiteAlpha.100">
                        <Box height={300} background="whiteAlpha.100"></Box>
                        <Box paddingY="8" paddingX="6">
                            <Heading marginBottom="4" size="md">
                                Here goes a sample title for any random article post I will write
                            </Heading>
                            <Text fontSize="lg">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...
                            </Text>
                        </Box>
                    </Box>
                    <Box border="1px" borderColor="whiteAlpha.100">
                        <Box height={300} background="whiteAlpha.100"></Box>
                        <Box paddingY="8" paddingX="6">
                            <Heading marginBottom="4" size="md">
                                Here goes a sample title for any random article post I will write
                            </Heading>
                            <Text fontSize="lg">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...
                            </Text>
                        </Box>
                    </Box>
                    <Box border="1px" borderColor="whiteAlpha.100">
                        <Box height={300} background="whiteAlpha.100"></Box>
                        <Box paddingY="8" paddingX="6">
                            <Heading marginBottom="4" size="md">
                                Here goes a sample title for any random article post I will write
                            </Heading>
                            <Text fontSize="lg">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...
                            </Text>
                        </Box>
                    </Box>
                </Grid>
            </Box>

        </div>
    )
}

HomePage.displayName = 'HomePage';

export default HomePage
