import type { NextPage } from "next";
import {
    Box,
    Button,
    Flex,
    Grid,
    Heading,
    IconButton,
    ListItem,
    Spacer,
    Text,
    useColorMode,
    useColorModeValue,
} from "@chakra-ui/react";
import { DownloadIcon } from "@heroicons/react/outline";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { decorateComponent } from "../utilities/decorateComponent";
import { useState } from "react";
import { Icon } from "~/common/components/elements/Icon/Icon";

const HomePage: NextPage = () => {
    const boxShadowColor = useColorModeValue(
        "whiteAlpha.100",
        "whiteAlpha.100"
    );
    const [posts] = useState([
        {
            title: "Here goes a sample title for any random article post I will write",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...",
        },
        {
            title: "Here goes a sample title for any random article post I will write",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...",
        },
        {
            title: "Here goes a sample title for any random article post I will write",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...",
        },
        {
            title: "Here goes a sample title for any random article post I will write",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...",
        },
        {
            title: "Here goes a sample title for any random article post I will write",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Scelerisque nisl porttitor congue sit viverra consec...",
        },
    ]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Daniel Hernández</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box
                flexDirection="column"
                alignItems="flex-start"
                marginBottom="48"
            >
                <Box
                    overflow="hidden"
                    marginY="6"
                    position="relative"
                    borderRadius="50%"
                    height="156px"
                    width="156px"
                >
                    <Image
                        width="156"
                        height="156"
                        src="/profile-light.png"
                    ></Image>
                </Box>
                <Heading color="secondary.default" size="lg" marginBottom="6">
                    Hi, I'm Daniel Hernández
                </Heading>
                <Heading size="3xl">
                    I bring to life{" "}
                    <Text
                        fontWeight="600"
                        color="primary.default"
                        display="inline"
                    >
                        stunning
                        <br /> web applications.
                    </Text>
                </Heading>

                <Text fontSize="xl" marginTop="6">
                    I’m a frontend developer based in Bogotá, CO with a strong
                    design & backend
                    <br /> experience. Currently working for ByPeople as
                    Technical Lead Engineer.
                </Text>
            </Box>

            <Box flexDirection="column" alignItems="flex-start">
                <Heading size="2xl">Latest blog posts</Heading>

                <Text fontSize="xl" marginTop="6" marginBottom="14">
                    I’m constantly writing about what I learn & sharing my
                    experiences on the
                    <br /> work. Hope you find useful content here or at least
                    learn something new.
                </Text>

                <Grid
                    width="100%"
                    templateColumns="repeat(auto-fill, minmax(360px, 1fr))"
                    gap={10}
                >
                    {posts.map((post, index) => (
                        <Box
                            key={index}
                            borderRadius="8px"
                            border="solid 2px"
                            borderColor="whiteAlpha.100"
                            transition="ease-in-out 100ms"
                            style={{
                                borderCollapse: "unset",
                            }}
                            _hover={{
                                boxShadow: `0px 0px 20px 0px var(--chakra-colors-primary-ghost)`,
                                borderWidth: `2px`,
                                borderColor: `primary.default`,
                            }}
                        >
                            <Box height={300} background="whiteAlpha.100"></Box>
                            <Box paddingY="8" paddingX="6">
                                <Heading marginBottom="4" size="md">
                                    {post.title}
                                </Heading>
                                <Text marginBottom="4" fontSize="md">
                                    {post.description}
                                </Text>
                                <Flex
                                    alignItems="center"
                                    justifyContent="space-between"
                                >
                                    <Button
                                        variant="link"
                                        colorScheme="primary"
                                        size="lg"
                                    >
                                        Read more...
                                    </Button>
                                    <Text color="whiteAlpha.600" fontSize="md">
                                        5 mins read - 18 Aug, 2021
                                    </Text>
                                </Flex>
                            </Box>
                        </Box>
                    ))}
                </Grid>
            </Box>
            <Spacer margin="6rem"></Spacer>
            <Box flexDirection="column" alignItems="flex-start">
                <Heading size="2xl">Recent Projects</Heading>

                <Text fontSize="xl" marginTop="6" marginBottom="14">
                    I enjoy work for amazing projects and missions. Also, I
                    usually spend part of<br /> my free time to build personal
                    projects. Check out some of them down here.
                </Text>

                <Grid
                    width="100%"
                    templateColumns="repeat(auto-fill, minmax(360px, 1fr))"
                    gap={10}
                >
                    {posts.map((post, index) => (
                        <Box
                            key={index}
                            borderRadius="8px"
                            border="solid 2px"
                            borderColor="whiteAlpha.100"
                            transition="ease-in-out 100ms"
                            style={{
                                borderCollapse: "unset",
                            }}
                            _hover={{
                                boxShadow: `0px 0px 20px 0px var(--chakra-colors-primary-ghost)`,
                                borderWidth: `2px`,
                                borderColor: `primary.default`,
                            }}
                        >
                            <Box height={300} background="whiteAlpha.100"></Box>
                            <Box paddingY="8" paddingX="6">
                                <Heading marginBottom="4" size="md">
                                    {post.title}
                                </Heading>
                                <Text marginBottom="4" fontSize="md">
                                    {post.description}
                                </Text>
                                <Flex
                                    alignItems="center"
                                    justifyContent="space-between"
                                >
                                    <Button
                                        variant="link"
                                        colorScheme="primary"
                                        size="lg"
                                    >
                                        Read more...
                                    </Button>
                                    <Text color="whiteAlpha.600" fontSize="md">
                                        5 mins read - 18 Aug, 2021
                                    </Text>
                                </Flex>
                            </Box>
                        </Box>
                    ))}
                </Grid>
            </Box>
            <Spacer margin="6rem"></Spacer>
            <Box
                position="relative"
                flexDirection="column"
                width="120%"
                height="1000px"
                alignItems="flex-start"
                overflow="hidden"
            >
                <Box
                    right="-10%"
                    width="100%"
                    height="1000px"
                    position="absolute"
                    zIndex="0"
                    _after={{
                        content: "''",
                        position: "relative",
                        display: "flex",
                        width: "100%",
                        height: "100%",
                        boxShadow: "-100px 0px 200px 150px #19171E inset",
                        zIndex: "10",
                    }}
                >
                    <Image
                        style={{
                            opacity: "1",
                            position: "relative",
                            objectFit: "contain",
                        }}
                        layout="fill"
                        src="/contactme.svg"
                    ></Image>
                </Box>
                <Flex
                    height="100%"
                    position="relative"
                    flexDirection="column"
                    justifyContent="center"
                    zIndex="10"
                >
                    <Heading color="primary.default" size="md" marginBottom="6">
                        Contact me
                    </Heading>
                    <Heading size="2xl">
                        I'm looking forward <br></br>to work with you
                    </Heading>

                    <Text
                        maxWidth="680px"
                        fontSize="xl"
                        marginTop="6"
                        marginBottom="14"
                    >
                        Have an amazing idea, project or team for me to work in?
                        Do I fill your expectatives? Please feel free to get in
                        touch with me anytime
                    </Text>
                    <Flex>
                        <Button
                            size="lg"
                            variant="solid"
                            colorScheme="primary"
                            marginRight="4"
                            rightIcon={<Icon name="Email"></Icon>}
                        >
                            Send me an email
                        </Button>
                        <Button
                            size="lg"
                            marginRight="4"
                            rightIcon={<Icon name="Linkedin"></Icon>}
                        >
                            Linkedin
                        </Button>
                        <Button
                            size="lg"
                            marginRight="4"
                            rightIcon={<Icon name="Twitter"></Icon>}
                        >
                            Twitter
                        </Button>
                    </Flex>
                    <Text
                        maxWidth="680px"
                        fontSize="xl"
                        marginTop="6"
                        marginBottom="14"
                    >
                        Also
                    </Text>
                </Flex>
            </Box>
        </div>
    );
};

HomePage.displayName = "HomePage";

export default HomePage;
